// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a2a.proto

package org.a2aproject.sdk.compat03.grpc;

public interface AgentExtensionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.AgentExtension)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The URI of the extension.
   * Example: "https://developers.google.com/identity/protocols/oauth2"
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <pre>
   * The URI of the extension.
   * Example: "https://developers.google.com/identity/protocols/oauth2"
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();

  /**
   * <pre>
   * A description of how this agent uses this extension.
   * Example: "Google OAuth 2.0 authentication"
   * </pre>
   *
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * A description of how this agent uses this extension.
   * Example: "Google OAuth 2.0 authentication"
   * </pre>
   *
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * Whether the client must follow specific requirements of the extension.
   * Example: false
   * </pre>
   *
   * <code>bool required = 3;</code>
   * @return The required.
   */
  boolean getRequired();

  /**
   * <pre>
   * Optional configuration for the extension.
   * </pre>
   *
   * <code>.google.protobuf.Struct params = 4;</code>
   * @return Whether the params field is set.
   */
  boolean hasParams();
  /**
   * <pre>
   * Optional configuration for the extension.
   * </pre>
   *
   * <code>.google.protobuf.Struct params = 4;</code>
   * @return The params.
   */
  com.google.protobuf.Struct getParams();
  /**
   * <pre>
   * Optional configuration for the extension.
   * </pre>
   *
   * <code>.google.protobuf.Struct params = 4;</code>
   */
  com.google.protobuf.StructOrBuilder getParamsOrBuilder();
}
