// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a2a.proto

package org.a2aproject.sdk.compat03.grpc;

public interface GetTaskPushNotificationConfigRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.GetTaskPushNotificationConfigRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name=tasks/{id}/pushNotificationConfigs/{push_id}
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * name=tasks/{id}/pushNotificationConfigs/{push_id}
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
