// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a2a.proto

package org.a2aproject.sdk.compat03.grpc;

/**
 * Protobuf type {@code a2a.v1.OAuthFlows}
 */
public final class OAuthFlows extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:a2a.v1.OAuthFlows)
    OAuthFlowsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OAuthFlows.newBuilder() to construct.
  private OAuthFlows(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OAuthFlows() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OAuthFlows();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OAuthFlows(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.Builder subBuilder = null;
            if (flowCase_ == 1) {
              subBuilder = ((org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow) flow_).toBuilder();
            }
            flow_ =
                input.readMessage(org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow) flow_);
              flow_ = subBuilder.buildPartial();
            }
            flowCase_ = 1;
            break;
          }
          case 18: {
            org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.Builder subBuilder = null;
            if (flowCase_ == 2) {
              subBuilder = ((org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow) flow_).toBuilder();
            }
            flow_ =
                input.readMessage(org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow) flow_);
              flow_ = subBuilder.buildPartial();
            }
            flowCase_ = 2;
            break;
          }
          case 26: {
            org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.Builder subBuilder = null;
            if (flowCase_ == 3) {
              subBuilder = ((org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow) flow_).toBuilder();
            }
            flow_ =
                input.readMessage(org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow) flow_);
              flow_ = subBuilder.buildPartial();
            }
            flowCase_ = 3;
            break;
          }
          case 34: {
            org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.Builder subBuilder = null;
            if (flowCase_ == 4) {
              subBuilder = ((org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow) flow_).toBuilder();
            }
            flow_ =
                input.readMessage(org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow) flow_);
              flow_ = subBuilder.buildPartial();
            }
            flowCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.a2aproject.sdk.compat03.grpc.A2A.internal_static_a2a_v1_OAuthFlows_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.a2aproject.sdk.compat03.grpc.A2A.internal_static_a2a_v1_OAuthFlows_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.a2aproject.sdk.compat03.grpc.OAuthFlows.class, org.a2aproject.sdk.compat03.grpc.OAuthFlows.Builder.class);
  }

  private int flowCase_ = 0;
  private java.lang.Object flow_;
  public enum FlowCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    AUTHORIZATION_CODE(1),
    CLIENT_CREDENTIALS(2),
    IMPLICIT(3),
    PASSWORD(4),
    FLOW_NOT_SET(0);
    private final int value;
    private FlowCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FlowCase valueOf(int value) {
      return forNumber(value);
    }

    public static FlowCase forNumber(int value) {
      switch (value) {
        case 1: return AUTHORIZATION_CODE;
        case 2: return CLIENT_CREDENTIALS;
        case 3: return IMPLICIT;
        case 4: return PASSWORD;
        case 0: return FLOW_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public FlowCase
  getFlowCase() {
    return FlowCase.forNumber(
        flowCase_);
  }

  public static final int AUTHORIZATION_CODE_FIELD_NUMBER = 1;
  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
   * @return Whether the authorizationCode field is set.
   */
  @java.lang.Override
  public boolean hasAuthorizationCode() {
    return flowCase_ == 1;
  }
  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
   * @return The authorizationCode.
   */
  @java.lang.Override
  public org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow getAuthorizationCode() {
    if (flowCase_ == 1) {
       return (org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow) flow_;
    }
    return org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlowOrBuilder getAuthorizationCodeOrBuilder() {
    if (flowCase_ == 1) {
       return (org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow) flow_;
    }
    return org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.getDefaultInstance();
  }

  public static final int CLIENT_CREDENTIALS_FIELD_NUMBER = 2;
  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
   * @return Whether the clientCredentials field is set.
   */
  @java.lang.Override
  public boolean hasClientCredentials() {
    return flowCase_ == 2;
  }
  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
   * @return The clientCredentials.
   */
  @java.lang.Override
  public org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow getClientCredentials() {
    if (flowCase_ == 2) {
       return (org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow) flow_;
    }
    return org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlowOrBuilder getClientCredentialsOrBuilder() {
    if (flowCase_ == 2) {
       return (org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow) flow_;
    }
    return org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.getDefaultInstance();
  }

  public static final int IMPLICIT_FIELD_NUMBER = 3;
  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
   * @return Whether the implicit field is set.
   */
  @java.lang.Override
  public boolean hasImplicit() {
    return flowCase_ == 3;
  }
  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
   * @return The implicit.
   */
  @java.lang.Override
  public org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow getImplicit() {
    if (flowCase_ == 3) {
       return (org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow) flow_;
    }
    return org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlowOrBuilder getImplicitOrBuilder() {
    if (flowCase_ == 3) {
       return (org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow) flow_;
    }
    return org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.getDefaultInstance();
  }

  public static final int PASSWORD_FIELD_NUMBER = 4;
  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
   * @return Whether the password field is set.
   */
  @java.lang.Override
  public boolean hasPassword() {
    return flowCase_ == 4;
  }
  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
   * @return The password.
   */
  @java.lang.Override
  public org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow getPassword() {
    if (flowCase_ == 4) {
       return (org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow) flow_;
    }
    return org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlowOrBuilder getPasswordOrBuilder() {
    if (flowCase_ == 4) {
       return (org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow) flow_;
    }
    return org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (flowCase_ == 1) {
      output.writeMessage(1, (org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow) flow_);
    }
    if (flowCase_ == 2) {
      output.writeMessage(2, (org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow) flow_);
    }
    if (flowCase_ == 3) {
      output.writeMessage(3, (org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow) flow_);
    }
    if (flowCase_ == 4) {
      output.writeMessage(4, (org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow) flow_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (flowCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow) flow_);
    }
    if (flowCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow) flow_);
    }
    if (flowCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow) flow_);
    }
    if (flowCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow) flow_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.a2aproject.sdk.compat03.grpc.OAuthFlows)) {
      return super.equals(obj);
    }
    org.a2aproject.sdk.compat03.grpc.OAuthFlows other = (org.a2aproject.sdk.compat03.grpc.OAuthFlows) obj;

    if (!getFlowCase().equals(other.getFlowCase())) return false;
    switch (flowCase_) {
      case 1:
        if (!getAuthorizationCode()
            .equals(other.getAuthorizationCode())) return false;
        break;
      case 2:
        if (!getClientCredentials()
            .equals(other.getClientCredentials())) return false;
        break;
      case 3:
        if (!getImplicit()
            .equals(other.getImplicit())) return false;
        break;
      case 4:
        if (!getPassword()
            .equals(other.getPassword())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (flowCase_) {
      case 1:
        hash = (37 * hash) + AUTHORIZATION_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getAuthorizationCode().hashCode();
        break;
      case 2:
        hash = (37 * hash) + CLIENT_CREDENTIALS_FIELD_NUMBER;
        hash = (53 * hash) + getClientCredentials().hashCode();
        break;
      case 3:
        hash = (37 * hash) + IMPLICIT_FIELD_NUMBER;
        hash = (53 * hash) + getImplicit().hashCode();
        break;
      case 4:
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.a2aproject.sdk.compat03.grpc.OAuthFlows prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code a2a.v1.OAuthFlows}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.OAuthFlows)
      org.a2aproject.sdk.compat03.grpc.OAuthFlowsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.a2aproject.sdk.compat03.grpc.A2A.internal_static_a2a_v1_OAuthFlows_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.a2aproject.sdk.compat03.grpc.A2A.internal_static_a2a_v1_OAuthFlows_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.a2aproject.sdk.compat03.grpc.OAuthFlows.class, org.a2aproject.sdk.compat03.grpc.OAuthFlows.Builder.class);
    }

    // Construct using org.a2aproject.sdk.compat03.grpc.OAuthFlows.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      flowCase_ = 0;
      flow_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.a2aproject.sdk.compat03.grpc.A2A.internal_static_a2a_v1_OAuthFlows_descriptor;
    }

    @java.lang.Override
    public org.a2aproject.sdk.compat03.grpc.OAuthFlows getDefaultInstanceForType() {
      return org.a2aproject.sdk.compat03.grpc.OAuthFlows.getDefaultInstance();
    }

    @java.lang.Override
    public org.a2aproject.sdk.compat03.grpc.OAuthFlows build() {
      org.a2aproject.sdk.compat03.grpc.OAuthFlows result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.a2aproject.sdk.compat03.grpc.OAuthFlows buildPartial() {
      org.a2aproject.sdk.compat03.grpc.OAuthFlows result = new org.a2aproject.sdk.compat03.grpc.OAuthFlows(this);
      if (flowCase_ == 1) {
        if (authorizationCodeBuilder_ == null) {
          result.flow_ = flow_;
        } else {
          result.flow_ = authorizationCodeBuilder_.build();
        }
      }
      if (flowCase_ == 2) {
        if (clientCredentialsBuilder_ == null) {
          result.flow_ = flow_;
        } else {
          result.flow_ = clientCredentialsBuilder_.build();
        }
      }
      if (flowCase_ == 3) {
        if (implicitBuilder_ == null) {
          result.flow_ = flow_;
        } else {
          result.flow_ = implicitBuilder_.build();
        }
      }
      if (flowCase_ == 4) {
        if (passwordBuilder_ == null) {
          result.flow_ = flow_;
        } else {
          result.flow_ = passwordBuilder_.build();
        }
      }
      result.flowCase_ = flowCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.a2aproject.sdk.compat03.grpc.OAuthFlows) {
        return mergeFrom((org.a2aproject.sdk.compat03.grpc.OAuthFlows)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.a2aproject.sdk.compat03.grpc.OAuthFlows other) {
      if (other == org.a2aproject.sdk.compat03.grpc.OAuthFlows.getDefaultInstance()) return this;
      switch (other.getFlowCase()) {
        case AUTHORIZATION_CODE: {
          mergeAuthorizationCode(other.getAuthorizationCode());
          break;
        }
        case CLIENT_CREDENTIALS: {
          mergeClientCredentials(other.getClientCredentials());
          break;
        }
        case IMPLICIT: {
          mergeImplicit(other.getImplicit());
          break;
        }
        case PASSWORD: {
          mergePassword(other.getPassword());
          break;
        }
        case FLOW_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.a2aproject.sdk.compat03.grpc.OAuthFlows parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.a2aproject.sdk.compat03.grpc.OAuthFlows) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int flowCase_ = 0;
    private java.lang.Object flow_;
    public FlowCase
        getFlowCase() {
      return FlowCase.forNumber(
          flowCase_);
    }

    public Builder clearFlow() {
      flowCase_ = 0;
      flow_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow, org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlowOrBuilder> authorizationCodeBuilder_;
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
     * @return Whether the authorizationCode field is set.
     */
    @java.lang.Override
    public boolean hasAuthorizationCode() {
      return flowCase_ == 1;
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
     * @return The authorizationCode.
     */
    @java.lang.Override
    public org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow getAuthorizationCode() {
      if (authorizationCodeBuilder_ == null) {
        if (flowCase_ == 1) {
          return (org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow) flow_;
        }
        return org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.getDefaultInstance();
      } else {
        if (flowCase_ == 1) {
          return authorizationCodeBuilder_.getMessage();
        }
        return org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
     */
    public Builder setAuthorizationCode(org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow value) {
      if (authorizationCodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flow_ = value;
        onChanged();
      } else {
        authorizationCodeBuilder_.setMessage(value);
      }
      flowCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
     */
    public Builder setAuthorizationCode(
        org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.Builder builderForValue) {
      if (authorizationCodeBuilder_ == null) {
        flow_ = builderForValue.build();
        onChanged();
      } else {
        authorizationCodeBuilder_.setMessage(builderForValue.build());
      }
      flowCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
     */
    public Builder mergeAuthorizationCode(org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow value) {
      if (authorizationCodeBuilder_ == null) {
        if (flowCase_ == 1 &&
            flow_ != org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.getDefaultInstance()) {
          flow_ = org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.newBuilder((org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow) flow_)
              .mergeFrom(value).buildPartial();
        } else {
          flow_ = value;
        }
        onChanged();
      } else {
        if (flowCase_ == 1) {
          authorizationCodeBuilder_.mergeFrom(value);
        }
        authorizationCodeBuilder_.setMessage(value);
      }
      flowCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
     */
    public Builder clearAuthorizationCode() {
      if (authorizationCodeBuilder_ == null) {
        if (flowCase_ == 1) {
          flowCase_ = 0;
          flow_ = null;
          onChanged();
        }
      } else {
        if (flowCase_ == 1) {
          flowCase_ = 0;
          flow_ = null;
        }
        authorizationCodeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
     */
    public org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.Builder getAuthorizationCodeBuilder() {
      return getAuthorizationCodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
     */
    @java.lang.Override
    public org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlowOrBuilder getAuthorizationCodeOrBuilder() {
      if ((flowCase_ == 1) && (authorizationCodeBuilder_ != null)) {
        return authorizationCodeBuilder_.getMessageOrBuilder();
      } else {
        if (flowCase_ == 1) {
          return (org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow) flow_;
        }
        return org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow, org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlowOrBuilder> 
        getAuthorizationCodeFieldBuilder() {
      if (authorizationCodeBuilder_ == null) {
        if (!(flowCase_ == 1)) {
          flow_ = org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.getDefaultInstance();
        }
        authorizationCodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow, org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlowOrBuilder>(
                (org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow) flow_,
                getParentForChildren(),
                isClean());
        flow_ = null;
      }
      flowCase_ = 1;
      onChanged();;
      return authorizationCodeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow, org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlowOrBuilder> clientCredentialsBuilder_;
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
     * @return Whether the clientCredentials field is set.
     */
    @java.lang.Override
    public boolean hasClientCredentials() {
      return flowCase_ == 2;
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
     * @return The clientCredentials.
     */
    @java.lang.Override
    public org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow getClientCredentials() {
      if (clientCredentialsBuilder_ == null) {
        if (flowCase_ == 2) {
          return (org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow) flow_;
        }
        return org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.getDefaultInstance();
      } else {
        if (flowCase_ == 2) {
          return clientCredentialsBuilder_.getMessage();
        }
        return org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
     */
    public Builder setClientCredentials(org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow value) {
      if (clientCredentialsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flow_ = value;
        onChanged();
      } else {
        clientCredentialsBuilder_.setMessage(value);
      }
      flowCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
     */
    public Builder setClientCredentials(
        org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.Builder builderForValue) {
      if (clientCredentialsBuilder_ == null) {
        flow_ = builderForValue.build();
        onChanged();
      } else {
        clientCredentialsBuilder_.setMessage(builderForValue.build());
      }
      flowCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
     */
    public Builder mergeClientCredentials(org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow value) {
      if (clientCredentialsBuilder_ == null) {
        if (flowCase_ == 2 &&
            flow_ != org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.getDefaultInstance()) {
          flow_ = org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.newBuilder((org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow) flow_)
              .mergeFrom(value).buildPartial();
        } else {
          flow_ = value;
        }
        onChanged();
      } else {
        if (flowCase_ == 2) {
          clientCredentialsBuilder_.mergeFrom(value);
        }
        clientCredentialsBuilder_.setMessage(value);
      }
      flowCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
     */
    public Builder clearClientCredentials() {
      if (clientCredentialsBuilder_ == null) {
        if (flowCase_ == 2) {
          flowCase_ = 0;
          flow_ = null;
          onChanged();
        }
      } else {
        if (flowCase_ == 2) {
          flowCase_ = 0;
          flow_ = null;
        }
        clientCredentialsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
     */
    public org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.Builder getClientCredentialsBuilder() {
      return getClientCredentialsFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
     */
    @java.lang.Override
    public org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlowOrBuilder getClientCredentialsOrBuilder() {
      if ((flowCase_ == 2) && (clientCredentialsBuilder_ != null)) {
        return clientCredentialsBuilder_.getMessageOrBuilder();
      } else {
        if (flowCase_ == 2) {
          return (org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow) flow_;
        }
        return org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow, org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlowOrBuilder> 
        getClientCredentialsFieldBuilder() {
      if (clientCredentialsBuilder_ == null) {
        if (!(flowCase_ == 2)) {
          flow_ = org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.getDefaultInstance();
        }
        clientCredentialsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow, org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlowOrBuilder>(
                (org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow) flow_,
                getParentForChildren(),
                isClean());
        flow_ = null;
      }
      flowCase_ = 2;
      onChanged();;
      return clientCredentialsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow, org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlowOrBuilder> implicitBuilder_;
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
     * @return Whether the implicit field is set.
     */
    @java.lang.Override
    public boolean hasImplicit() {
      return flowCase_ == 3;
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
     * @return The implicit.
     */
    @java.lang.Override
    public org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow getImplicit() {
      if (implicitBuilder_ == null) {
        if (flowCase_ == 3) {
          return (org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow) flow_;
        }
        return org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.getDefaultInstance();
      } else {
        if (flowCase_ == 3) {
          return implicitBuilder_.getMessage();
        }
        return org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
     */
    public Builder setImplicit(org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow value) {
      if (implicitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flow_ = value;
        onChanged();
      } else {
        implicitBuilder_.setMessage(value);
      }
      flowCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
     */
    public Builder setImplicit(
        org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.Builder builderForValue) {
      if (implicitBuilder_ == null) {
        flow_ = builderForValue.build();
        onChanged();
      } else {
        implicitBuilder_.setMessage(builderForValue.build());
      }
      flowCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
     */
    public Builder mergeImplicit(org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow value) {
      if (implicitBuilder_ == null) {
        if (flowCase_ == 3 &&
            flow_ != org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.getDefaultInstance()) {
          flow_ = org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.newBuilder((org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow) flow_)
              .mergeFrom(value).buildPartial();
        } else {
          flow_ = value;
        }
        onChanged();
      } else {
        if (flowCase_ == 3) {
          implicitBuilder_.mergeFrom(value);
        }
        implicitBuilder_.setMessage(value);
      }
      flowCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
     */
    public Builder clearImplicit() {
      if (implicitBuilder_ == null) {
        if (flowCase_ == 3) {
          flowCase_ = 0;
          flow_ = null;
          onChanged();
        }
      } else {
        if (flowCase_ == 3) {
          flowCase_ = 0;
          flow_ = null;
        }
        implicitBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
     */
    public org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.Builder getImplicitBuilder() {
      return getImplicitFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
     */
    @java.lang.Override
    public org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlowOrBuilder getImplicitOrBuilder() {
      if ((flowCase_ == 3) && (implicitBuilder_ != null)) {
        return implicitBuilder_.getMessageOrBuilder();
      } else {
        if (flowCase_ == 3) {
          return (org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow) flow_;
        }
        return org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow, org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlowOrBuilder> 
        getImplicitFieldBuilder() {
      if (implicitBuilder_ == null) {
        if (!(flowCase_ == 3)) {
          flow_ = org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.getDefaultInstance();
        }
        implicitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow, org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlowOrBuilder>(
                (org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow) flow_,
                getParentForChildren(),
                isClean());
        flow_ = null;
      }
      flowCase_ = 3;
      onChanged();;
      return implicitBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow, org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlowOrBuilder> passwordBuilder_;
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
     * @return Whether the password field is set.
     */
    @java.lang.Override
    public boolean hasPassword() {
      return flowCase_ == 4;
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
     * @return The password.
     */
    @java.lang.Override
    public org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow getPassword() {
      if (passwordBuilder_ == null) {
        if (flowCase_ == 4) {
          return (org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow) flow_;
        }
        return org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.getDefaultInstance();
      } else {
        if (flowCase_ == 4) {
          return passwordBuilder_.getMessage();
        }
        return org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
     */
    public Builder setPassword(org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow value) {
      if (passwordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flow_ = value;
        onChanged();
      } else {
        passwordBuilder_.setMessage(value);
      }
      flowCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
     */
    public Builder setPassword(
        org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.Builder builderForValue) {
      if (passwordBuilder_ == null) {
        flow_ = builderForValue.build();
        onChanged();
      } else {
        passwordBuilder_.setMessage(builderForValue.build());
      }
      flowCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
     */
    public Builder mergePassword(org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow value) {
      if (passwordBuilder_ == null) {
        if (flowCase_ == 4 &&
            flow_ != org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.getDefaultInstance()) {
          flow_ = org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.newBuilder((org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow) flow_)
              .mergeFrom(value).buildPartial();
        } else {
          flow_ = value;
        }
        onChanged();
      } else {
        if (flowCase_ == 4) {
          passwordBuilder_.mergeFrom(value);
        }
        passwordBuilder_.setMessage(value);
      }
      flowCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
     */
    public Builder clearPassword() {
      if (passwordBuilder_ == null) {
        if (flowCase_ == 4) {
          flowCase_ = 0;
          flow_ = null;
          onChanged();
        }
      } else {
        if (flowCase_ == 4) {
          flowCase_ = 0;
          flow_ = null;
        }
        passwordBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
     */
    public org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.Builder getPasswordBuilder() {
      return getPasswordFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
     */
    @java.lang.Override
    public org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlowOrBuilder getPasswordOrBuilder() {
      if ((flowCase_ == 4) && (passwordBuilder_ != null)) {
        return passwordBuilder_.getMessageOrBuilder();
      } else {
        if (flowCase_ == 4) {
          return (org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow) flow_;
        }
        return org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow, org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlowOrBuilder> 
        getPasswordFieldBuilder() {
      if (passwordBuilder_ == null) {
        if (!(flowCase_ == 4)) {
          flow_ = org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.getDefaultInstance();
        }
        passwordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow, org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow.Builder, org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlowOrBuilder>(
                (org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow) flow_,
                getParentForChildren(),
                isClean());
        flow_ = null;
      }
      flowCase_ = 4;
      onChanged();;
      return passwordBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:a2a.v1.OAuthFlows)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.OAuthFlows)
  private static final org.a2aproject.sdk.compat03.grpc.OAuthFlows DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.a2aproject.sdk.compat03.grpc.OAuthFlows();
  }

  public static org.a2aproject.sdk.compat03.grpc.OAuthFlows getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OAuthFlows>
      PARSER = new com.google.protobuf.AbstractParser<OAuthFlows>() {
    @java.lang.Override
    public OAuthFlows parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OAuthFlows(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OAuthFlows> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OAuthFlows> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.a2aproject.sdk.compat03.grpc.OAuthFlows getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

