// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a2a.proto

package org.a2aproject.sdk.compat03.grpc;

public interface OpenIdConnectSecuritySchemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.OpenIdConnectSecurityScheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Description of this security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Description of this security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * Well-known URL to discover the [[OpenID-Connect-Discovery]] provider
   * metadata.
   * </pre>
   *
   * <code>string open_id_connect_url = 2;</code>
   * @return The openIdConnectUrl.
   */
  java.lang.String getOpenIdConnectUrl();
  /**
   * <pre>
   * Well-known URL to discover the [[OpenID-Connect-Discovery]] provider
   * metadata.
   * </pre>
   *
   * <code>string open_id_connect_url = 2;</code>
   * @return The bytes for openIdConnectUrl.
   */
  com.google.protobuf.ByteString
      getOpenIdConnectUrlBytes();
}
