// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a2a.proto

package org.a2aproject.sdk.compat03.grpc;

public interface SecurityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.Security)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1;</code>
   */
  int getSchemesCount();
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1;</code>
   */
  boolean containsSchemes(
      java.lang.String key);
  /**
   * Use {@link #getSchemesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.a2aproject.sdk.compat03.grpc.StringList>
  getSchemes();
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1;</code>
   */
  java.util.Map<java.lang.String, org.a2aproject.sdk.compat03.grpc.StringList>
  getSchemesMap();
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1;</code>
   */

  org.a2aproject.sdk.compat03.grpc.StringList getSchemesOrDefault(
      java.lang.String key,
      org.a2aproject.sdk.compat03.grpc.StringList defaultValue);
  /**
   * <code>map&lt;string, .a2a.v1.StringList&gt; schemes = 1;</code>
   */

  org.a2aproject.sdk.compat03.grpc.StringList getSchemesOrThrow(
      java.lang.String key);
}
