// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a2a.proto

package org.a2aproject.sdk.compat03.grpc;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.a2a.v1.Task task = 1;</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <code>.a2a.v1.Task task = 1;</code>
   * @return The task.
   */
  org.a2aproject.sdk.compat03.grpc.Task getTask();
  /**
   * <code>.a2a.v1.Task task = 1;</code>
   */
  org.a2aproject.sdk.compat03.grpc.TaskOrBuilder getTaskOrBuilder();

  /**
   * <code>.a2a.v1.Message msg = 2[json_name = "message"];</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>.a2a.v1.Message msg = 2[json_name = "message"];</code>
   * @return The msg.
   */
  org.a2aproject.sdk.compat03.grpc.Message getMsg();
  /**
   * <code>.a2a.v1.Message msg = 2[json_name = "message"];</code>
   */
  org.a2aproject.sdk.compat03.grpc.MessageOrBuilder getMsgOrBuilder();

  /**
   * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3;</code>
   * @return Whether the statusUpdate field is set.
   */
  boolean hasStatusUpdate();
  /**
   * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3;</code>
   * @return The statusUpdate.
   */
  org.a2aproject.sdk.compat03.grpc.TaskStatusUpdateEvent getStatusUpdate();
  /**
   * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3;</code>
   */
  org.a2aproject.sdk.compat03.grpc.TaskStatusUpdateEventOrBuilder getStatusUpdateOrBuilder();

  /**
   * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4;</code>
   * @return Whether the artifactUpdate field is set.
   */
  boolean hasArtifactUpdate();
  /**
   * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4;</code>
   * @return The artifactUpdate.
   */
  org.a2aproject.sdk.compat03.grpc.TaskArtifactUpdateEvent getArtifactUpdate();
  /**
   * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4;</code>
   */
  org.a2aproject.sdk.compat03.grpc.TaskArtifactUpdateEventOrBuilder getArtifactUpdateOrBuilder();

  public org.a2aproject.sdk.compat03.grpc.StreamResponse.PayloadCase getPayloadCase();
}
