// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a2a.proto

package org.a2aproject.sdk.grpc;

/**
 * <pre>
 * Represents a distinct capability or function that an agent can perform.
 * </pre>
 *
 * Protobuf type {@code lf.a2a.v1.AgentSkill}
 */
public final class AgentSkill extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lf.a2a.v1.AgentSkill)
    AgentSkillOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AgentSkill.newBuilder() to construct.
  private AgentSkill(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AgentSkill() {
    id_ = "";
    name_ = "";
    description_ = "";
    tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    examples_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    inputModes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    outputModes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    securityRequirements_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AgentSkill();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AgentSkill(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              tags_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            tags_.add(s);
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              examples_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            examples_.add(s);
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              inputModes_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            inputModes_.add(s);
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              outputModes_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000008;
            }
            outputModes_.add(s);
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              securityRequirements_ = new java.util.ArrayList<org.a2aproject.sdk.grpc.SecurityRequirement>();
              mutable_bitField0_ |= 0x00000010;
            }
            securityRequirements_.add(
                input.readMessage(org.a2aproject.sdk.grpc.SecurityRequirement.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        examples_ = examples_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        inputModes_ = inputModes_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        outputModes_ = outputModes_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        securityRequirements_ = java.util.Collections.unmodifiableList(securityRequirements_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_AgentSkill_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_AgentSkill_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.a2aproject.sdk.grpc.AgentSkill.class, org.a2aproject.sdk.grpc.AgentSkill.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * A unique identifier for the agent's skill.
   * </pre>
   *
   * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A unique identifier for the agent's skill.
   * </pre>
   *
   * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * A human-readable name for the skill.
   * </pre>
   *
   * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A human-readable name for the skill.
   * </pre>
   *
   * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <pre>
   * A detailed description of the skill.
   * </pre>
   *
   * <code>string description = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A detailed description of the skill.
   * </pre>
   *
   * <code>string description = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList tags_;
  /**
   * <pre>
   * A set of keywords describing the skill's capabilities.
   * </pre>
   *
   * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <pre>
   * A set of keywords describing the skill's capabilities.
   * </pre>
   *
   * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <pre>
   * A set of keywords describing the skill's capabilities.
   * </pre>
   *
   * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <pre>
   * A set of keywords describing the skill's capabilities.
   * </pre>
   *
   * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int EXAMPLES_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList examples_;
  /**
   * <pre>
   * Example prompts or scenarios that this skill can handle.
   * </pre>
   *
   * <code>repeated string examples = 5;</code>
   * @return A list containing the examples.
   */
  public com.google.protobuf.ProtocolStringList
      getExamplesList() {
    return examples_;
  }
  /**
   * <pre>
   * Example prompts or scenarios that this skill can handle.
   * </pre>
   *
   * <code>repeated string examples = 5;</code>
   * @return The count of examples.
   */
  public int getExamplesCount() {
    return examples_.size();
  }
  /**
   * <pre>
   * Example prompts or scenarios that this skill can handle.
   * </pre>
   *
   * <code>repeated string examples = 5;</code>
   * @param index The index of the element to return.
   * @return The examples at the given index.
   */
  public java.lang.String getExamples(int index) {
    return examples_.get(index);
  }
  /**
   * <pre>
   * Example prompts or scenarios that this skill can handle.
   * </pre>
   *
   * <code>repeated string examples = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the examples at the given index.
   */
  public com.google.protobuf.ByteString
      getExamplesBytes(int index) {
    return examples_.getByteString(index);
  }

  public static final int INPUT_MODES_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList inputModes_;
  /**
   * <pre>
   * The set of supported input media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string input_modes = 6;</code>
   * @return A list containing the inputModes.
   */
  public com.google.protobuf.ProtocolStringList
      getInputModesList() {
    return inputModes_;
  }
  /**
   * <pre>
   * The set of supported input media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string input_modes = 6;</code>
   * @return The count of inputModes.
   */
  public int getInputModesCount() {
    return inputModes_.size();
  }
  /**
   * <pre>
   * The set of supported input media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string input_modes = 6;</code>
   * @param index The index of the element to return.
   * @return The inputModes at the given index.
   */
  public java.lang.String getInputModes(int index) {
    return inputModes_.get(index);
  }
  /**
   * <pre>
   * The set of supported input media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string input_modes = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the inputModes at the given index.
   */
  public com.google.protobuf.ByteString
      getInputModesBytes(int index) {
    return inputModes_.getByteString(index);
  }

  public static final int OUTPUT_MODES_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList outputModes_;
  /**
   * <pre>
   * The set of supported output media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string output_modes = 7;</code>
   * @return A list containing the outputModes.
   */
  public com.google.protobuf.ProtocolStringList
      getOutputModesList() {
    return outputModes_;
  }
  /**
   * <pre>
   * The set of supported output media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string output_modes = 7;</code>
   * @return The count of outputModes.
   */
  public int getOutputModesCount() {
    return outputModes_.size();
  }
  /**
   * <pre>
   * The set of supported output media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string output_modes = 7;</code>
   * @param index The index of the element to return.
   * @return The outputModes at the given index.
   */
  public java.lang.String getOutputModes(int index) {
    return outputModes_.get(index);
  }
  /**
   * <pre>
   * The set of supported output media types for this skill, overriding the agent's defaults.
   * </pre>
   *
   * <code>repeated string output_modes = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the outputModes at the given index.
   */
  public com.google.protobuf.ByteString
      getOutputModesBytes(int index) {
    return outputModes_.getByteString(index);
  }

  public static final int SECURITY_REQUIREMENTS_FIELD_NUMBER = 8;
  private java.util.List<org.a2aproject.sdk.grpc.SecurityRequirement> securityRequirements_;
  /**
   * <pre>
   * Security schemes necessary for this skill.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
   */
  @java.lang.Override
  public java.util.List<org.a2aproject.sdk.grpc.SecurityRequirement> getSecurityRequirementsList() {
    return securityRequirements_;
  }
  /**
   * <pre>
   * Security schemes necessary for this skill.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.a2aproject.sdk.grpc.SecurityRequirementOrBuilder> 
      getSecurityRequirementsOrBuilderList() {
    return securityRequirements_;
  }
  /**
   * <pre>
   * Security schemes necessary for this skill.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
   */
  @java.lang.Override
  public int getSecurityRequirementsCount() {
    return securityRequirements_.size();
  }
  /**
   * <pre>
   * Security schemes necessary for this skill.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.grpc.SecurityRequirement getSecurityRequirements(int index) {
    return securityRequirements_.get(index);
  }
  /**
   * <pre>
   * Security schemes necessary for this skill.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.grpc.SecurityRequirementOrBuilder getSecurityRequirementsOrBuilder(
      int index) {
    return securityRequirements_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tags_.getRaw(i));
    }
    for (int i = 0; i < examples_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, examples_.getRaw(i));
    }
    for (int i = 0; i < inputModes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, inputModes_.getRaw(i));
    }
    for (int i = 0; i < outputModes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, outputModes_.getRaw(i));
    }
    for (int i = 0; i < securityRequirements_.size(); i++) {
      output.writeMessage(8, securityRequirements_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < examples_.size(); i++) {
        dataSize += computeStringSizeNoTag(examples_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getExamplesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < inputModes_.size(); i++) {
        dataSize += computeStringSizeNoTag(inputModes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInputModesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < outputModes_.size(); i++) {
        dataSize += computeStringSizeNoTag(outputModes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOutputModesList().size();
    }
    for (int i = 0; i < securityRequirements_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, securityRequirements_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.a2aproject.sdk.grpc.AgentSkill)) {
      return super.equals(obj);
    }
    org.a2aproject.sdk.grpc.AgentSkill other = (org.a2aproject.sdk.grpc.AgentSkill) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (!getExamplesList()
        .equals(other.getExamplesList())) return false;
    if (!getInputModesList()
        .equals(other.getInputModesList())) return false;
    if (!getOutputModesList()
        .equals(other.getOutputModesList())) return false;
    if (!getSecurityRequirementsList()
        .equals(other.getSecurityRequirementsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    if (getExamplesCount() > 0) {
      hash = (37 * hash) + EXAMPLES_FIELD_NUMBER;
      hash = (53 * hash) + getExamplesList().hashCode();
    }
    if (getInputModesCount() > 0) {
      hash = (37 * hash) + INPUT_MODES_FIELD_NUMBER;
      hash = (53 * hash) + getInputModesList().hashCode();
    }
    if (getOutputModesCount() > 0) {
      hash = (37 * hash) + OUTPUT_MODES_FIELD_NUMBER;
      hash = (53 * hash) + getOutputModesList().hashCode();
    }
    if (getSecurityRequirementsCount() > 0) {
      hash = (37 * hash) + SECURITY_REQUIREMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityRequirementsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.a2aproject.sdk.grpc.AgentSkill parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.grpc.AgentSkill parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.AgentSkill parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.grpc.AgentSkill parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.AgentSkill parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.grpc.AgentSkill parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.AgentSkill parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.grpc.AgentSkill parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.AgentSkill parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.grpc.AgentSkill parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.AgentSkill parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.grpc.AgentSkill parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.a2aproject.sdk.grpc.AgentSkill prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents a distinct capability or function that an agent can perform.
   * </pre>
   *
   * Protobuf type {@code lf.a2a.v1.AgentSkill}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lf.a2a.v1.AgentSkill)
      org.a2aproject.sdk.grpc.AgentSkillOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_AgentSkill_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_AgentSkill_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.a2aproject.sdk.grpc.AgentSkill.class, org.a2aproject.sdk.grpc.AgentSkill.Builder.class);
    }

    // Construct using org.a2aproject.sdk.grpc.AgentSkill.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSecurityRequirementsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      description_ = "";

      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      examples_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      inputModes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      outputModes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (securityRequirementsBuilder_ == null) {
        securityRequirements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        securityRequirementsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_AgentSkill_descriptor;
    }

    @java.lang.Override
    public org.a2aproject.sdk.grpc.AgentSkill getDefaultInstanceForType() {
      return org.a2aproject.sdk.grpc.AgentSkill.getDefaultInstance();
    }

    @java.lang.Override
    public org.a2aproject.sdk.grpc.AgentSkill build() {
      org.a2aproject.sdk.grpc.AgentSkill result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.a2aproject.sdk.grpc.AgentSkill buildPartial() {
      org.a2aproject.sdk.grpc.AgentSkill result = new org.a2aproject.sdk.grpc.AgentSkill(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.name_ = name_;
      result.description_ = description_;
      if (((bitField0_ & 0x00000001) != 0)) {
        tags_ = tags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.tags_ = tags_;
      if (((bitField0_ & 0x00000002) != 0)) {
        examples_ = examples_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.examples_ = examples_;
      if (((bitField0_ & 0x00000004) != 0)) {
        inputModes_ = inputModes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.inputModes_ = inputModes_;
      if (((bitField0_ & 0x00000008) != 0)) {
        outputModes_ = outputModes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.outputModes_ = outputModes_;
      if (securityRequirementsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          securityRequirements_ = java.util.Collections.unmodifiableList(securityRequirements_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.securityRequirements_ = securityRequirements_;
      } else {
        result.securityRequirements_ = securityRequirementsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.a2aproject.sdk.grpc.AgentSkill) {
        return mergeFrom((org.a2aproject.sdk.grpc.AgentSkill)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.a2aproject.sdk.grpc.AgentSkill other) {
      if (other == org.a2aproject.sdk.grpc.AgentSkill.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (!other.examples_.isEmpty()) {
        if (examples_.isEmpty()) {
          examples_ = other.examples_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureExamplesIsMutable();
          examples_.addAll(other.examples_);
        }
        onChanged();
      }
      if (!other.inputModes_.isEmpty()) {
        if (inputModes_.isEmpty()) {
          inputModes_ = other.inputModes_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureInputModesIsMutable();
          inputModes_.addAll(other.inputModes_);
        }
        onChanged();
      }
      if (!other.outputModes_.isEmpty()) {
        if (outputModes_.isEmpty()) {
          outputModes_ = other.outputModes_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureOutputModesIsMutable();
          outputModes_.addAll(other.outputModes_);
        }
        onChanged();
      }
      if (securityRequirementsBuilder_ == null) {
        if (!other.securityRequirements_.isEmpty()) {
          if (securityRequirements_.isEmpty()) {
            securityRequirements_ = other.securityRequirements_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSecurityRequirementsIsMutable();
            securityRequirements_.addAll(other.securityRequirements_);
          }
          onChanged();
        }
      } else {
        if (!other.securityRequirements_.isEmpty()) {
          if (securityRequirementsBuilder_.isEmpty()) {
            securityRequirementsBuilder_.dispose();
            securityRequirementsBuilder_ = null;
            securityRequirements_ = other.securityRequirements_;
            bitField0_ = (bitField0_ & ~0x00000010);
            securityRequirementsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSecurityRequirementsFieldBuilder() : null;
          } else {
            securityRequirementsBuilder_.addAllMessages(other.securityRequirements_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.a2aproject.sdk.grpc.AgentSkill parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.a2aproject.sdk.grpc.AgentSkill) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * A unique identifier for the agent's skill.
     * </pre>
     *
     * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A unique identifier for the agent's skill.
     * </pre>
     *
     * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A unique identifier for the agent's skill.
     * </pre>
     *
     * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A unique identifier for the agent's skill.
     * </pre>
     *
     * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A unique identifier for the agent's skill.
     * </pre>
     *
     * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * A human-readable name for the skill.
     * </pre>
     *
     * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A human-readable name for the skill.
     * </pre>
     *
     * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A human-readable name for the skill.
     * </pre>
     *
     * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A human-readable name for the skill.
     * </pre>
     *
     * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A human-readable name for the skill.
     * </pre>
     *
     * <code>string name = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * A detailed description of the skill.
     * </pre>
     *
     * <code>string description = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A detailed description of the skill.
     * </pre>
     *
     * <code>string description = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A detailed description of the skill.
     * </pre>
     *
     * <code>string description = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A detailed description of the skill.
     * </pre>
     *
     * <code>string description = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A detailed description of the skill.
     * </pre>
     *
     * <code>string description = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTagsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * A set of keywords describing the skill's capabilities.
     * </pre>
     *
     * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_.getUnmodifiableView();
    }
    /**
     * <pre>
     * A set of keywords describing the skill's capabilities.
     * </pre>
     *
     * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <pre>
     * A set of keywords describing the skill's capabilities.
     * </pre>
     *
     * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <pre>
     * A set of keywords describing the skill's capabilities.
     * </pre>
     *
     * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <pre>
     * A set of keywords describing the skill's capabilities.
     * </pre>
     *
     * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of keywords describing the skill's capabilities.
     * </pre>
     *
     * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of keywords describing the skill's capabilities.
     * </pre>
     *
     * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of keywords describing the skill's capabilities.
     * </pre>
     *
     * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A set of keywords describing the skill's capabilities.
     * </pre>
     *
     * <code>repeated string tags = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList examples_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureExamplesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        examples_ = new com.google.protobuf.LazyStringArrayList(examples_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * Example prompts or scenarios that this skill can handle.
     * </pre>
     *
     * <code>repeated string examples = 5;</code>
     * @return A list containing the examples.
     */
    public com.google.protobuf.ProtocolStringList
        getExamplesList() {
      return examples_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Example prompts or scenarios that this skill can handle.
     * </pre>
     *
     * <code>repeated string examples = 5;</code>
     * @return The count of examples.
     */
    public int getExamplesCount() {
      return examples_.size();
    }
    /**
     * <pre>
     * Example prompts or scenarios that this skill can handle.
     * </pre>
     *
     * <code>repeated string examples = 5;</code>
     * @param index The index of the element to return.
     * @return The examples at the given index.
     */
    public java.lang.String getExamples(int index) {
      return examples_.get(index);
    }
    /**
     * <pre>
     * Example prompts or scenarios that this skill can handle.
     * </pre>
     *
     * <code>repeated string examples = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the examples at the given index.
     */
    public com.google.protobuf.ByteString
        getExamplesBytes(int index) {
      return examples_.getByteString(index);
    }
    /**
     * <pre>
     * Example prompts or scenarios that this skill can handle.
     * </pre>
     *
     * <code>repeated string examples = 5;</code>
     * @param index The index to set the value at.
     * @param value The examples to set.
     * @return This builder for chaining.
     */
    public Builder setExamples(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureExamplesIsMutable();
      examples_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Example prompts or scenarios that this skill can handle.
     * </pre>
     *
     * <code>repeated string examples = 5;</code>
     * @param value The examples to add.
     * @return This builder for chaining.
     */
    public Builder addExamples(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureExamplesIsMutable();
      examples_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Example prompts or scenarios that this skill can handle.
     * </pre>
     *
     * <code>repeated string examples = 5;</code>
     * @param values The examples to add.
     * @return This builder for chaining.
     */
    public Builder addAllExamples(
        java.lang.Iterable<java.lang.String> values) {
      ensureExamplesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, examples_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Example prompts or scenarios that this skill can handle.
     * </pre>
     *
     * <code>repeated string examples = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearExamples() {
      examples_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Example prompts or scenarios that this skill can handle.
     * </pre>
     *
     * <code>repeated string examples = 5;</code>
     * @param value The bytes of the examples to add.
     * @return This builder for chaining.
     */
    public Builder addExamplesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureExamplesIsMutable();
      examples_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList inputModes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureInputModesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        inputModes_ = new com.google.protobuf.LazyStringArrayList(inputModes_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * The set of supported input media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string input_modes = 6;</code>
     * @return A list containing the inputModes.
     */
    public com.google.protobuf.ProtocolStringList
        getInputModesList() {
      return inputModes_.getUnmodifiableView();
    }
    /**
     * <pre>
     * The set of supported input media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string input_modes = 6;</code>
     * @return The count of inputModes.
     */
    public int getInputModesCount() {
      return inputModes_.size();
    }
    /**
     * <pre>
     * The set of supported input media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string input_modes = 6;</code>
     * @param index The index of the element to return.
     * @return The inputModes at the given index.
     */
    public java.lang.String getInputModes(int index) {
      return inputModes_.get(index);
    }
    /**
     * <pre>
     * The set of supported input media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string input_modes = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the inputModes at the given index.
     */
    public com.google.protobuf.ByteString
        getInputModesBytes(int index) {
      return inputModes_.getByteString(index);
    }
    /**
     * <pre>
     * The set of supported input media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string input_modes = 6;</code>
     * @param index The index to set the value at.
     * @param value The inputModes to set.
     * @return This builder for chaining.
     */
    public Builder setInputModes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInputModesIsMutable();
      inputModes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of supported input media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string input_modes = 6;</code>
     * @param value The inputModes to add.
     * @return This builder for chaining.
     */
    public Builder addInputModes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInputModesIsMutable();
      inputModes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of supported input media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string input_modes = 6;</code>
     * @param values The inputModes to add.
     * @return This builder for chaining.
     */
    public Builder addAllInputModes(
        java.lang.Iterable<java.lang.String> values) {
      ensureInputModesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, inputModes_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of supported input media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string input_modes = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearInputModes() {
      inputModes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of supported input media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string input_modes = 6;</code>
     * @param value The bytes of the inputModes to add.
     * @return This builder for chaining.
     */
    public Builder addInputModesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureInputModesIsMutable();
      inputModes_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList outputModes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureOutputModesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        outputModes_ = new com.google.protobuf.LazyStringArrayList(outputModes_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <pre>
     * The set of supported output media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string output_modes = 7;</code>
     * @return A list containing the outputModes.
     */
    public com.google.protobuf.ProtocolStringList
        getOutputModesList() {
      return outputModes_.getUnmodifiableView();
    }
    /**
     * <pre>
     * The set of supported output media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string output_modes = 7;</code>
     * @return The count of outputModes.
     */
    public int getOutputModesCount() {
      return outputModes_.size();
    }
    /**
     * <pre>
     * The set of supported output media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string output_modes = 7;</code>
     * @param index The index of the element to return.
     * @return The outputModes at the given index.
     */
    public java.lang.String getOutputModes(int index) {
      return outputModes_.get(index);
    }
    /**
     * <pre>
     * The set of supported output media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string output_modes = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the outputModes at the given index.
     */
    public com.google.protobuf.ByteString
        getOutputModesBytes(int index) {
      return outputModes_.getByteString(index);
    }
    /**
     * <pre>
     * The set of supported output media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string output_modes = 7;</code>
     * @param index The index to set the value at.
     * @param value The outputModes to set.
     * @return This builder for chaining.
     */
    public Builder setOutputModes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputModesIsMutable();
      outputModes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of supported output media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string output_modes = 7;</code>
     * @param value The outputModes to add.
     * @return This builder for chaining.
     */
    public Builder addOutputModes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputModesIsMutable();
      outputModes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of supported output media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string output_modes = 7;</code>
     * @param values The outputModes to add.
     * @return This builder for chaining.
     */
    public Builder addAllOutputModes(
        java.lang.Iterable<java.lang.String> values) {
      ensureOutputModesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, outputModes_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of supported output media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string output_modes = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputModes() {
      outputModes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The set of supported output media types for this skill, overriding the agent's defaults.
     * </pre>
     *
     * <code>repeated string output_modes = 7;</code>
     * @param value The bytes of the outputModes to add.
     * @return This builder for chaining.
     */
    public Builder addOutputModesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureOutputModesIsMutable();
      outputModes_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<org.a2aproject.sdk.grpc.SecurityRequirement> securityRequirements_ =
      java.util.Collections.emptyList();
    private void ensureSecurityRequirementsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        securityRequirements_ = new java.util.ArrayList<org.a2aproject.sdk.grpc.SecurityRequirement>(securityRequirements_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.a2aproject.sdk.grpc.SecurityRequirement, org.a2aproject.sdk.grpc.SecurityRequirement.Builder, org.a2aproject.sdk.grpc.SecurityRequirementOrBuilder> securityRequirementsBuilder_;

    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public java.util.List<org.a2aproject.sdk.grpc.SecurityRequirement> getSecurityRequirementsList() {
      if (securityRequirementsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(securityRequirements_);
      } else {
        return securityRequirementsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public int getSecurityRequirementsCount() {
      if (securityRequirementsBuilder_ == null) {
        return securityRequirements_.size();
      } else {
        return securityRequirementsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public org.a2aproject.sdk.grpc.SecurityRequirement getSecurityRequirements(int index) {
      if (securityRequirementsBuilder_ == null) {
        return securityRequirements_.get(index);
      } else {
        return securityRequirementsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public Builder setSecurityRequirements(
        int index, org.a2aproject.sdk.grpc.SecurityRequirement value) {
      if (securityRequirementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecurityRequirementsIsMutable();
        securityRequirements_.set(index, value);
        onChanged();
      } else {
        securityRequirementsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public Builder setSecurityRequirements(
        int index, org.a2aproject.sdk.grpc.SecurityRequirement.Builder builderForValue) {
      if (securityRequirementsBuilder_ == null) {
        ensureSecurityRequirementsIsMutable();
        securityRequirements_.set(index, builderForValue.build());
        onChanged();
      } else {
        securityRequirementsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public Builder addSecurityRequirements(org.a2aproject.sdk.grpc.SecurityRequirement value) {
      if (securityRequirementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecurityRequirementsIsMutable();
        securityRequirements_.add(value);
        onChanged();
      } else {
        securityRequirementsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public Builder addSecurityRequirements(
        int index, org.a2aproject.sdk.grpc.SecurityRequirement value) {
      if (securityRequirementsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecurityRequirementsIsMutable();
        securityRequirements_.add(index, value);
        onChanged();
      } else {
        securityRequirementsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public Builder addSecurityRequirements(
        org.a2aproject.sdk.grpc.SecurityRequirement.Builder builderForValue) {
      if (securityRequirementsBuilder_ == null) {
        ensureSecurityRequirementsIsMutable();
        securityRequirements_.add(builderForValue.build());
        onChanged();
      } else {
        securityRequirementsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public Builder addSecurityRequirements(
        int index, org.a2aproject.sdk.grpc.SecurityRequirement.Builder builderForValue) {
      if (securityRequirementsBuilder_ == null) {
        ensureSecurityRequirementsIsMutable();
        securityRequirements_.add(index, builderForValue.build());
        onChanged();
      } else {
        securityRequirementsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public Builder addAllSecurityRequirements(
        java.lang.Iterable<? extends org.a2aproject.sdk.grpc.SecurityRequirement> values) {
      if (securityRequirementsBuilder_ == null) {
        ensureSecurityRequirementsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, securityRequirements_);
        onChanged();
      } else {
        securityRequirementsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public Builder clearSecurityRequirements() {
      if (securityRequirementsBuilder_ == null) {
        securityRequirements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        securityRequirementsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public Builder removeSecurityRequirements(int index) {
      if (securityRequirementsBuilder_ == null) {
        ensureSecurityRequirementsIsMutable();
        securityRequirements_.remove(index);
        onChanged();
      } else {
        securityRequirementsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public org.a2aproject.sdk.grpc.SecurityRequirement.Builder getSecurityRequirementsBuilder(
        int index) {
      return getSecurityRequirementsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public org.a2aproject.sdk.grpc.SecurityRequirementOrBuilder getSecurityRequirementsOrBuilder(
        int index) {
      if (securityRequirementsBuilder_ == null) {
        return securityRequirements_.get(index);  } else {
        return securityRequirementsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public java.util.List<? extends org.a2aproject.sdk.grpc.SecurityRequirementOrBuilder> 
         getSecurityRequirementsOrBuilderList() {
      if (securityRequirementsBuilder_ != null) {
        return securityRequirementsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(securityRequirements_);
      }
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public org.a2aproject.sdk.grpc.SecurityRequirement.Builder addSecurityRequirementsBuilder() {
      return getSecurityRequirementsFieldBuilder().addBuilder(
          org.a2aproject.sdk.grpc.SecurityRequirement.getDefaultInstance());
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public org.a2aproject.sdk.grpc.SecurityRequirement.Builder addSecurityRequirementsBuilder(
        int index) {
      return getSecurityRequirementsFieldBuilder().addBuilder(
          index, org.a2aproject.sdk.grpc.SecurityRequirement.getDefaultInstance());
    }
    /**
     * <pre>
     * Security schemes necessary for this skill.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.SecurityRequirement security_requirements = 8;</code>
     */
    public java.util.List<org.a2aproject.sdk.grpc.SecurityRequirement.Builder> 
         getSecurityRequirementsBuilderList() {
      return getSecurityRequirementsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.a2aproject.sdk.grpc.SecurityRequirement, org.a2aproject.sdk.grpc.SecurityRequirement.Builder, org.a2aproject.sdk.grpc.SecurityRequirementOrBuilder> 
        getSecurityRequirementsFieldBuilder() {
      if (securityRequirementsBuilder_ == null) {
        securityRequirementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.a2aproject.sdk.grpc.SecurityRequirement, org.a2aproject.sdk.grpc.SecurityRequirement.Builder, org.a2aproject.sdk.grpc.SecurityRequirementOrBuilder>(
                securityRequirements_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        securityRequirements_ = null;
      }
      return securityRequirementsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lf.a2a.v1.AgentSkill)
  }

  // @@protoc_insertion_point(class_scope:lf.a2a.v1.AgentSkill)
  private static final org.a2aproject.sdk.grpc.AgentSkill DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.a2aproject.sdk.grpc.AgentSkill();
  }

  public static org.a2aproject.sdk.grpc.AgentSkill getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgentSkill>
      PARSER = new com.google.protobuf.AbstractParser<AgentSkill>() {
    @java.lang.Override
    public AgentSkill parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AgentSkill(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AgentSkill> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgentSkill> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.a2aproject.sdk.grpc.AgentSkill getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

