// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a2a.proto

package org.a2aproject.sdk.grpc;

/**
 * <pre>
 * Defines optional capabilities supported by an agent.
 * </pre>
 *
 * Protobuf type {@code lf.a2a.v1.AgentCapabilities}
 */
public final class AgentCapabilities extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lf.a2a.v1.AgentCapabilities)
    AgentCapabilitiesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AgentCapabilities.newBuilder() to construct.
  private AgentCapabilities(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AgentCapabilities() {
    extensions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AgentCapabilities();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AgentCapabilities(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            streaming_ = input.readBool();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            pushNotifications_ = input.readBool();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              extensions_ = new java.util.ArrayList<org.a2aproject.sdk.grpc.AgentExtension>();
              mutable_bitField0_ |= 0x00000004;
            }
            extensions_.add(
                input.readMessage(org.a2aproject.sdk.grpc.AgentExtension.parser(), extensionRegistry));
            break;
          }
          case 32: {
            bitField0_ |= 0x00000004;
            extendedAgentCard_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        extensions_ = java.util.Collections.unmodifiableList(extensions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_AgentCapabilities_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_AgentCapabilities_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.a2aproject.sdk.grpc.AgentCapabilities.class, org.a2aproject.sdk.grpc.AgentCapabilities.Builder.class);
  }

  private int bitField0_;
  public static final int STREAMING_FIELD_NUMBER = 1;
  private boolean streaming_;
  /**
   * <pre>
   * Indicates if the agent supports streaming responses.
   * </pre>
   *
   * <code>bool streaming = 1;</code>
   * @return Whether the streaming field is set.
   */
  @java.lang.Override
  public boolean hasStreaming() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Indicates if the agent supports streaming responses.
   * </pre>
   *
   * <code>bool streaming = 1;</code>
   * @return The streaming.
   */
  @java.lang.Override
  public boolean getStreaming() {
    return streaming_;
  }

  public static final int PUSH_NOTIFICATIONS_FIELD_NUMBER = 2;
  private boolean pushNotifications_;
  /**
   * <pre>
   * Indicates if the agent supports sending push notifications for asynchronous task updates.
   * </pre>
   *
   * <code>bool push_notifications = 2;</code>
   * @return Whether the pushNotifications field is set.
   */
  @java.lang.Override
  public boolean hasPushNotifications() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Indicates if the agent supports sending push notifications for asynchronous task updates.
   * </pre>
   *
   * <code>bool push_notifications = 2;</code>
   * @return The pushNotifications.
   */
  @java.lang.Override
  public boolean getPushNotifications() {
    return pushNotifications_;
  }

  public static final int EXTENSIONS_FIELD_NUMBER = 3;
  private java.util.List<org.a2aproject.sdk.grpc.AgentExtension> extensions_;
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<org.a2aproject.sdk.grpc.AgentExtension> getExtensionsList() {
    return extensions_;
  }
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.a2aproject.sdk.grpc.AgentExtensionOrBuilder> 
      getExtensionsOrBuilderList() {
    return extensions_;
  }
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
   */
  @java.lang.Override
  public int getExtensionsCount() {
    return extensions_.size();
  }
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.grpc.AgentExtension getExtensions(int index) {
    return extensions_.get(index);
  }
  /**
   * <pre>
   * A list of protocol extensions supported by the agent.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.grpc.AgentExtensionOrBuilder getExtensionsOrBuilder(
      int index) {
    return extensions_.get(index);
  }

  public static final int EXTENDED_AGENT_CARD_FIELD_NUMBER = 4;
  private boolean extendedAgentCard_;
  /**
   * <pre>
   * Indicates if the agent supports providing an extended agent card when authenticated.
   * </pre>
   *
   * <code>bool extended_agent_card = 4;</code>
   * @return Whether the extendedAgentCard field is set.
   */
  @java.lang.Override
  public boolean hasExtendedAgentCard() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Indicates if the agent supports providing an extended agent card when authenticated.
   * </pre>
   *
   * <code>bool extended_agent_card = 4;</code>
   * @return The extendedAgentCard.
   */
  @java.lang.Override
  public boolean getExtendedAgentCard() {
    return extendedAgentCard_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, streaming_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, pushNotifications_);
    }
    for (int i = 0; i < extensions_.size(); i++) {
      output.writeMessage(3, extensions_.get(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(4, extendedAgentCard_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, streaming_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, pushNotifications_);
    }
    for (int i = 0; i < extensions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, extensions_.get(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, extendedAgentCard_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.a2aproject.sdk.grpc.AgentCapabilities)) {
      return super.equals(obj);
    }
    org.a2aproject.sdk.grpc.AgentCapabilities other = (org.a2aproject.sdk.grpc.AgentCapabilities) obj;

    if (hasStreaming() != other.hasStreaming()) return false;
    if (hasStreaming()) {
      if (getStreaming()
          != other.getStreaming()) return false;
    }
    if (hasPushNotifications() != other.hasPushNotifications()) return false;
    if (hasPushNotifications()) {
      if (getPushNotifications()
          != other.getPushNotifications()) return false;
    }
    if (!getExtensionsList()
        .equals(other.getExtensionsList())) return false;
    if (hasExtendedAgentCard() != other.hasExtendedAgentCard()) return false;
    if (hasExtendedAgentCard()) {
      if (getExtendedAgentCard()
          != other.getExtendedAgentCard()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStreaming()) {
      hash = (37 * hash) + STREAMING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStreaming());
    }
    if (hasPushNotifications()) {
      hash = (37 * hash) + PUSH_NOTIFICATIONS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPushNotifications());
    }
    if (getExtensionsCount() > 0) {
      hash = (37 * hash) + EXTENSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getExtensionsList().hashCode();
    }
    if (hasExtendedAgentCard()) {
      hash = (37 * hash) + EXTENDED_AGENT_CARD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getExtendedAgentCard());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.a2aproject.sdk.grpc.AgentCapabilities parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.grpc.AgentCapabilities parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.AgentCapabilities parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.grpc.AgentCapabilities parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.AgentCapabilities parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.grpc.AgentCapabilities parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.AgentCapabilities parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.grpc.AgentCapabilities parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.AgentCapabilities parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.grpc.AgentCapabilities parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.AgentCapabilities parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.grpc.AgentCapabilities parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.a2aproject.sdk.grpc.AgentCapabilities prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Defines optional capabilities supported by an agent.
   * </pre>
   *
   * Protobuf type {@code lf.a2a.v1.AgentCapabilities}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lf.a2a.v1.AgentCapabilities)
      org.a2aproject.sdk.grpc.AgentCapabilitiesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_AgentCapabilities_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_AgentCapabilities_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.a2aproject.sdk.grpc.AgentCapabilities.class, org.a2aproject.sdk.grpc.AgentCapabilities.Builder.class);
    }

    // Construct using org.a2aproject.sdk.grpc.AgentCapabilities.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getExtensionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      streaming_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      pushNotifications_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (extensionsBuilder_ == null) {
        extensions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        extensionsBuilder_.clear();
      }
      extendedAgentCard_ = false;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_AgentCapabilities_descriptor;
    }

    @java.lang.Override
    public org.a2aproject.sdk.grpc.AgentCapabilities getDefaultInstanceForType() {
      return org.a2aproject.sdk.grpc.AgentCapabilities.getDefaultInstance();
    }

    @java.lang.Override
    public org.a2aproject.sdk.grpc.AgentCapabilities build() {
      org.a2aproject.sdk.grpc.AgentCapabilities result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.a2aproject.sdk.grpc.AgentCapabilities buildPartial() {
      org.a2aproject.sdk.grpc.AgentCapabilities result = new org.a2aproject.sdk.grpc.AgentCapabilities(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.streaming_ = streaming_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pushNotifications_ = pushNotifications_;
        to_bitField0_ |= 0x00000002;
      }
      if (extensionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          extensions_ = java.util.Collections.unmodifiableList(extensions_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.extensions_ = extensions_;
      } else {
        result.extensions_ = extensionsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.extendedAgentCard_ = extendedAgentCard_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.a2aproject.sdk.grpc.AgentCapabilities) {
        return mergeFrom((org.a2aproject.sdk.grpc.AgentCapabilities)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.a2aproject.sdk.grpc.AgentCapabilities other) {
      if (other == org.a2aproject.sdk.grpc.AgentCapabilities.getDefaultInstance()) return this;
      if (other.hasStreaming()) {
        setStreaming(other.getStreaming());
      }
      if (other.hasPushNotifications()) {
        setPushNotifications(other.getPushNotifications());
      }
      if (extensionsBuilder_ == null) {
        if (!other.extensions_.isEmpty()) {
          if (extensions_.isEmpty()) {
            extensions_ = other.extensions_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureExtensionsIsMutable();
            extensions_.addAll(other.extensions_);
          }
          onChanged();
        }
      } else {
        if (!other.extensions_.isEmpty()) {
          if (extensionsBuilder_.isEmpty()) {
            extensionsBuilder_.dispose();
            extensionsBuilder_ = null;
            extensions_ = other.extensions_;
            bitField0_ = (bitField0_ & ~0x00000004);
            extensionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExtensionsFieldBuilder() : null;
          } else {
            extensionsBuilder_.addAllMessages(other.extensions_);
          }
        }
      }
      if (other.hasExtendedAgentCard()) {
        setExtendedAgentCard(other.getExtendedAgentCard());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.a2aproject.sdk.grpc.AgentCapabilities parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.a2aproject.sdk.grpc.AgentCapabilities) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean streaming_ ;
    /**
     * <pre>
     * Indicates if the agent supports streaming responses.
     * </pre>
     *
     * <code>bool streaming = 1;</code>
     * @return Whether the streaming field is set.
     */
    @java.lang.Override
    public boolean hasStreaming() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Indicates if the agent supports streaming responses.
     * </pre>
     *
     * <code>bool streaming = 1;</code>
     * @return The streaming.
     */
    @java.lang.Override
    public boolean getStreaming() {
      return streaming_;
    }
    /**
     * <pre>
     * Indicates if the agent supports streaming responses.
     * </pre>
     *
     * <code>bool streaming = 1;</code>
     * @param value The streaming to set.
     * @return This builder for chaining.
     */
    public Builder setStreaming(boolean value) {
      bitField0_ |= 0x00000001;
      streaming_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates if the agent supports streaming responses.
     * </pre>
     *
     * <code>bool streaming = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreaming() {
      bitField0_ = (bitField0_ & ~0x00000001);
      streaming_ = false;
      onChanged();
      return this;
    }

    private boolean pushNotifications_ ;
    /**
     * <pre>
     * Indicates if the agent supports sending push notifications for asynchronous task updates.
     * </pre>
     *
     * <code>bool push_notifications = 2;</code>
     * @return Whether the pushNotifications field is set.
     */
    @java.lang.Override
    public boolean hasPushNotifications() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Indicates if the agent supports sending push notifications for asynchronous task updates.
     * </pre>
     *
     * <code>bool push_notifications = 2;</code>
     * @return The pushNotifications.
     */
    @java.lang.Override
    public boolean getPushNotifications() {
      return pushNotifications_;
    }
    /**
     * <pre>
     * Indicates if the agent supports sending push notifications for asynchronous task updates.
     * </pre>
     *
     * <code>bool push_notifications = 2;</code>
     * @param value The pushNotifications to set.
     * @return This builder for chaining.
     */
    public Builder setPushNotifications(boolean value) {
      bitField0_ |= 0x00000002;
      pushNotifications_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates if the agent supports sending push notifications for asynchronous task updates.
     * </pre>
     *
     * <code>bool push_notifications = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPushNotifications() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pushNotifications_ = false;
      onChanged();
      return this;
    }

    private java.util.List<org.a2aproject.sdk.grpc.AgentExtension> extensions_ =
      java.util.Collections.emptyList();
    private void ensureExtensionsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        extensions_ = new java.util.ArrayList<org.a2aproject.sdk.grpc.AgentExtension>(extensions_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.a2aproject.sdk.grpc.AgentExtension, org.a2aproject.sdk.grpc.AgentExtension.Builder, org.a2aproject.sdk.grpc.AgentExtensionOrBuilder> extensionsBuilder_;

    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public java.util.List<org.a2aproject.sdk.grpc.AgentExtension> getExtensionsList() {
      if (extensionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(extensions_);
      } else {
        return extensionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public int getExtensionsCount() {
      if (extensionsBuilder_ == null) {
        return extensions_.size();
      } else {
        return extensionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public org.a2aproject.sdk.grpc.AgentExtension getExtensions(int index) {
      if (extensionsBuilder_ == null) {
        return extensions_.get(index);
      } else {
        return extensionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder setExtensions(
        int index, org.a2aproject.sdk.grpc.AgentExtension value) {
      if (extensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionsIsMutable();
        extensions_.set(index, value);
        onChanged();
      } else {
        extensionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder setExtensions(
        int index, org.a2aproject.sdk.grpc.AgentExtension.Builder builderForValue) {
      if (extensionsBuilder_ == null) {
        ensureExtensionsIsMutable();
        extensions_.set(index, builderForValue.build());
        onChanged();
      } else {
        extensionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder addExtensions(org.a2aproject.sdk.grpc.AgentExtension value) {
      if (extensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionsIsMutable();
        extensions_.add(value);
        onChanged();
      } else {
        extensionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder addExtensions(
        int index, org.a2aproject.sdk.grpc.AgentExtension value) {
      if (extensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtensionsIsMutable();
        extensions_.add(index, value);
        onChanged();
      } else {
        extensionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder addExtensions(
        org.a2aproject.sdk.grpc.AgentExtension.Builder builderForValue) {
      if (extensionsBuilder_ == null) {
        ensureExtensionsIsMutable();
        extensions_.add(builderForValue.build());
        onChanged();
      } else {
        extensionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder addExtensions(
        int index, org.a2aproject.sdk.grpc.AgentExtension.Builder builderForValue) {
      if (extensionsBuilder_ == null) {
        ensureExtensionsIsMutable();
        extensions_.add(index, builderForValue.build());
        onChanged();
      } else {
        extensionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder addAllExtensions(
        java.lang.Iterable<? extends org.a2aproject.sdk.grpc.AgentExtension> values) {
      if (extensionsBuilder_ == null) {
        ensureExtensionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, extensions_);
        onChanged();
      } else {
        extensionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder clearExtensions() {
      if (extensionsBuilder_ == null) {
        extensions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        extensionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public Builder removeExtensions(int index) {
      if (extensionsBuilder_ == null) {
        ensureExtensionsIsMutable();
        extensions_.remove(index);
        onChanged();
      } else {
        extensionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public org.a2aproject.sdk.grpc.AgentExtension.Builder getExtensionsBuilder(
        int index) {
      return getExtensionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public org.a2aproject.sdk.grpc.AgentExtensionOrBuilder getExtensionsOrBuilder(
        int index) {
      if (extensionsBuilder_ == null) {
        return extensions_.get(index);  } else {
        return extensionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public java.util.List<? extends org.a2aproject.sdk.grpc.AgentExtensionOrBuilder> 
         getExtensionsOrBuilderList() {
      if (extensionsBuilder_ != null) {
        return extensionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(extensions_);
      }
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public org.a2aproject.sdk.grpc.AgentExtension.Builder addExtensionsBuilder() {
      return getExtensionsFieldBuilder().addBuilder(
          org.a2aproject.sdk.grpc.AgentExtension.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public org.a2aproject.sdk.grpc.AgentExtension.Builder addExtensionsBuilder(
        int index) {
      return getExtensionsFieldBuilder().addBuilder(
          index, org.a2aproject.sdk.grpc.AgentExtension.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of protocol extensions supported by the agent.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.AgentExtension extensions = 3;</code>
     */
    public java.util.List<org.a2aproject.sdk.grpc.AgentExtension.Builder> 
         getExtensionsBuilderList() {
      return getExtensionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.a2aproject.sdk.grpc.AgentExtension, org.a2aproject.sdk.grpc.AgentExtension.Builder, org.a2aproject.sdk.grpc.AgentExtensionOrBuilder> 
        getExtensionsFieldBuilder() {
      if (extensionsBuilder_ == null) {
        extensionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.a2aproject.sdk.grpc.AgentExtension, org.a2aproject.sdk.grpc.AgentExtension.Builder, org.a2aproject.sdk.grpc.AgentExtensionOrBuilder>(
                extensions_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        extensions_ = null;
      }
      return extensionsBuilder_;
    }

    private boolean extendedAgentCard_ ;
    /**
     * <pre>
     * Indicates if the agent supports providing an extended agent card when authenticated.
     * </pre>
     *
     * <code>bool extended_agent_card = 4;</code>
     * @return Whether the extendedAgentCard field is set.
     */
    @java.lang.Override
    public boolean hasExtendedAgentCard() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Indicates if the agent supports providing an extended agent card when authenticated.
     * </pre>
     *
     * <code>bool extended_agent_card = 4;</code>
     * @return The extendedAgentCard.
     */
    @java.lang.Override
    public boolean getExtendedAgentCard() {
      return extendedAgentCard_;
    }
    /**
     * <pre>
     * Indicates if the agent supports providing an extended agent card when authenticated.
     * </pre>
     *
     * <code>bool extended_agent_card = 4;</code>
     * @param value The extendedAgentCard to set.
     * @return This builder for chaining.
     */
    public Builder setExtendedAgentCard(boolean value) {
      bitField0_ |= 0x00000008;
      extendedAgentCard_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates if the agent supports providing an extended agent card when authenticated.
     * </pre>
     *
     * <code>bool extended_agent_card = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtendedAgentCard() {
      bitField0_ = (bitField0_ & ~0x00000008);
      extendedAgentCard_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lf.a2a.v1.AgentCapabilities)
  }

  // @@protoc_insertion_point(class_scope:lf.a2a.v1.AgentCapabilities)
  private static final org.a2aproject.sdk.grpc.AgentCapabilities DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.a2aproject.sdk.grpc.AgentCapabilities();
  }

  public static org.a2aproject.sdk.grpc.AgentCapabilities getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgentCapabilities>
      PARSER = new com.google.protobuf.AbstractParser<AgentCapabilities>() {
    @java.lang.Override
    public AgentCapabilities parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AgentCapabilities(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AgentCapabilities> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgentCapabilities> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.a2aproject.sdk.grpc.AgentCapabilities getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

