// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a2a.proto

package org.a2aproject.sdk.grpc;

public interface GetExtendedAgentCardRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.GetExtendedAgentCardRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. Tenant ID, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * Optional. Tenant ID, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();
}
