// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a2a.proto

package org.a2aproject.sdk.grpc;

public interface MutualTlsSecuritySchemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.MutualTlsSecurityScheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An optional description for the security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * An optional description for the security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
