// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: a2a.proto

package org.a2aproject.sdk.grpc;

/**
 * <pre>
 * `Task` is the core unit of action for A2A. It has a current status
 * and when results are created for the task they are stored in the
 * artifact. If there are multiple turns for a task, these are stored in
 * history.
 * </pre>
 *
 * Protobuf type {@code lf.a2a.v1.Task}
 */
public final class Task extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lf.a2a.v1.Task)
    TaskOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Task.newBuilder() to construct.
  private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Task() {
    id_ = "";
    contextId_ = "";
    artifacts_ = java.util.Collections.emptyList();
    history_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Task();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Task(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            contextId_ = s;
            break;
          }
          case 26: {
            org.a2aproject.sdk.grpc.TaskStatus.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(org.a2aproject.sdk.grpc.TaskStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              artifacts_ = new java.util.ArrayList<org.a2aproject.sdk.grpc.Artifact>();
              mutable_bitField0_ |= 0x00000001;
            }
            artifacts_.add(
                input.readMessage(org.a2aproject.sdk.grpc.Artifact.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              history_ = new java.util.ArrayList<org.a2aproject.sdk.grpc.Message>();
              mutable_bitField0_ |= 0x00000002;
            }
            history_.add(
                input.readMessage(org.a2aproject.sdk.grpc.Message.parser(), extensionRegistry));
            break;
          }
          case 50: {
            com.google.protobuf.Struct.Builder subBuilder = null;
            if (metadata_ != null) {
              subBuilder = metadata_.toBuilder();
            }
            metadata_ = input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metadata_);
              metadata_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        artifacts_ = java.util.Collections.unmodifiableList(artifacts_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        history_ = java.util.Collections.unmodifiableList(history_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_Task_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_Task_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.a2aproject.sdk.grpc.Task.class, org.a2aproject.sdk.grpc.Task.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the task, generated by the server for a
   * new task.
   * </pre>
   *
   * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the task, generated by the server for a
   * new task.
   * </pre>
   *
   * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTEXT_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object contextId_;
  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the contextual collection of interactions
   * (tasks and messages).
   * </pre>
   *
   * <code>string context_id = 2;</code>
   * @return The contextId.
   */
  @java.lang.Override
  public java.lang.String getContextId() {
    java.lang.Object ref = contextId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contextId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the contextual collection of interactions
   * (tasks and messages).
   * </pre>
   *
   * <code>string context_id = 2;</code>
   * @return The bytes for contextId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContextIdBytes() {
    java.lang.Object ref = contextId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contextId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private org.a2aproject.sdk.grpc.TaskStatus status_;
  /**
   * <pre>
   * The current status of a `Task`, including `state` and a `message`.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <pre>
   * The current status of a `Task`, including `state` and a `message`.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The status.
   */
  @java.lang.Override
  public org.a2aproject.sdk.grpc.TaskStatus getStatus() {
    return status_ == null ? org.a2aproject.sdk.grpc.TaskStatus.getDefaultInstance() : status_;
  }
  /**
   * <pre>
   * The current status of a `Task`, including `state` and a `message`.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.grpc.TaskStatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int ARTIFACTS_FIELD_NUMBER = 4;
  private java.util.List<org.a2aproject.sdk.grpc.Artifact> artifacts_;
  /**
   * <pre>
   * A set of output artifacts for a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
   */
  @java.lang.Override
  public java.util.List<org.a2aproject.sdk.grpc.Artifact> getArtifactsList() {
    return artifacts_;
  }
  /**
   * <pre>
   * A set of output artifacts for a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.a2aproject.sdk.grpc.ArtifactOrBuilder> 
      getArtifactsOrBuilderList() {
    return artifacts_;
  }
  /**
   * <pre>
   * A set of output artifacts for a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
   */
  @java.lang.Override
  public int getArtifactsCount() {
    return artifacts_.size();
  }
  /**
   * <pre>
   * A set of output artifacts for a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.grpc.Artifact getArtifacts(int index) {
    return artifacts_.get(index);
  }
  /**
   * <pre>
   * A set of output artifacts for a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.grpc.ArtifactOrBuilder getArtifactsOrBuilder(
      int index) {
    return artifacts_.get(index);
  }

  public static final int HISTORY_FIELD_NUMBER = 5;
  private java.util.List<org.a2aproject.sdk.grpc.Message> history_;
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Message history = 5;</code>
   */
  @java.lang.Override
  public java.util.List<org.a2aproject.sdk.grpc.Message> getHistoryList() {
    return history_;
  }
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Message history = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.a2aproject.sdk.grpc.MessageOrBuilder> 
      getHistoryOrBuilderList() {
    return history_;
  }
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Message history = 5;</code>
   */
  @java.lang.Override
  public int getHistoryCount() {
    return history_.size();
  }
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Message history = 5;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.grpc.Message getHistory(int index) {
    return history_.get(index);
  }
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Message history = 5;</code>
   */
  @java.lang.Override
  public org.a2aproject.sdk.grpc.MessageOrBuilder getHistoryOrBuilder(
      int index) {
    return history_.get(index);
  }

  public static final int METADATA_FIELD_NUMBER = 6;
  private com.google.protobuf.Struct metadata_;
  /**
   * <pre>
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return metadata_ != null;
  }
  /**
   * <pre>
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getMetadata() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }
  /**
   * <pre>
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
    return getMetadata();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getContextIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contextId_);
    }
    if (status_ != null) {
      output.writeMessage(3, getStatus());
    }
    for (int i = 0; i < artifacts_.size(); i++) {
      output.writeMessage(4, artifacts_.get(i));
    }
    for (int i = 0; i < history_.size(); i++) {
      output.writeMessage(5, history_.get(i));
    }
    if (metadata_ != null) {
      output.writeMessage(6, getMetadata());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getContextIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contextId_);
    }
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStatus());
    }
    for (int i = 0; i < artifacts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, artifacts_.get(i));
    }
    for (int i = 0; i < history_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, history_.get(i));
    }
    if (metadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getMetadata());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.a2aproject.sdk.grpc.Task)) {
      return super.equals(obj);
    }
    org.a2aproject.sdk.grpc.Task other = (org.a2aproject.sdk.grpc.Task) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getContextId()
        .equals(other.getContextId())) return false;
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (!getArtifactsList()
        .equals(other.getArtifactsList())) return false;
    if (!getHistoryList()
        .equals(other.getHistoryList())) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CONTEXT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getContextId().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (getArtifactsCount() > 0) {
      hash = (37 * hash) + ARTIFACTS_FIELD_NUMBER;
      hash = (53 * hash) + getArtifactsList().hashCode();
    }
    if (getHistoryCount() > 0) {
      hash = (37 * hash) + HISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getHistoryList().hashCode();
    }
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.a2aproject.sdk.grpc.Task parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.grpc.Task parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.Task parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.grpc.Task parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.Task parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.a2aproject.sdk.grpc.Task parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.Task parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.grpc.Task parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.Task parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.grpc.Task parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.a2aproject.sdk.grpc.Task parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.a2aproject.sdk.grpc.Task parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.a2aproject.sdk.grpc.Task prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * `Task` is the core unit of action for A2A. It has a current status
   * and when results are created for the task they are stored in the
   * artifact. If there are multiple turns for a task, these are stored in
   * history.
   * </pre>
   *
   * Protobuf type {@code lf.a2a.v1.Task}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lf.a2a.v1.Task)
      org.a2aproject.sdk.grpc.TaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_Task_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.a2aproject.sdk.grpc.Task.class, org.a2aproject.sdk.grpc.Task.Builder.class);
    }

    // Construct using org.a2aproject.sdk.grpc.Task.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getArtifactsFieldBuilder();
        getHistoryFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      contextId_ = "";

      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      if (artifactsBuilder_ == null) {
        artifacts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        artifactsBuilder_.clear();
      }
      if (historyBuilder_ == null) {
        history_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        historyBuilder_.clear();
      }
      if (metadataBuilder_ == null) {
        metadata_ = null;
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.a2aproject.sdk.grpc.A2A.internal_static_lf_a2a_v1_Task_descriptor;
    }

    @java.lang.Override
    public org.a2aproject.sdk.grpc.Task getDefaultInstanceForType() {
      return org.a2aproject.sdk.grpc.Task.getDefaultInstance();
    }

    @java.lang.Override
    public org.a2aproject.sdk.grpc.Task build() {
      org.a2aproject.sdk.grpc.Task result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.a2aproject.sdk.grpc.Task buildPartial() {
      org.a2aproject.sdk.grpc.Task result = new org.a2aproject.sdk.grpc.Task(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.contextId_ = contextId_;
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      if (artifactsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          artifacts_ = java.util.Collections.unmodifiableList(artifacts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.artifacts_ = artifacts_;
      } else {
        result.artifacts_ = artifactsBuilder_.build();
      }
      if (historyBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          history_ = java.util.Collections.unmodifiableList(history_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.history_ = history_;
      } else {
        result.history_ = historyBuilder_.build();
      }
      if (metadataBuilder_ == null) {
        result.metadata_ = metadata_;
      } else {
        result.metadata_ = metadataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.a2aproject.sdk.grpc.Task) {
        return mergeFrom((org.a2aproject.sdk.grpc.Task)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.a2aproject.sdk.grpc.Task other) {
      if (other == org.a2aproject.sdk.grpc.Task.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getContextId().isEmpty()) {
        contextId_ = other.contextId_;
        onChanged();
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (artifactsBuilder_ == null) {
        if (!other.artifacts_.isEmpty()) {
          if (artifacts_.isEmpty()) {
            artifacts_ = other.artifacts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureArtifactsIsMutable();
            artifacts_.addAll(other.artifacts_);
          }
          onChanged();
        }
      } else {
        if (!other.artifacts_.isEmpty()) {
          if (artifactsBuilder_.isEmpty()) {
            artifactsBuilder_.dispose();
            artifactsBuilder_ = null;
            artifacts_ = other.artifacts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            artifactsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getArtifactsFieldBuilder() : null;
          } else {
            artifactsBuilder_.addAllMessages(other.artifacts_);
          }
        }
      }
      if (historyBuilder_ == null) {
        if (!other.history_.isEmpty()) {
          if (history_.isEmpty()) {
            history_ = other.history_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureHistoryIsMutable();
            history_.addAll(other.history_);
          }
          onChanged();
        }
      } else {
        if (!other.history_.isEmpty()) {
          if (historyBuilder_.isEmpty()) {
            historyBuilder_.dispose();
            historyBuilder_ = null;
            history_ = other.history_;
            bitField0_ = (bitField0_ & ~0x00000002);
            historyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHistoryFieldBuilder() : null;
          } else {
            historyBuilder_.addAllMessages(other.history_);
          }
        }
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.a2aproject.sdk.grpc.Task parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.a2aproject.sdk.grpc.Task) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Unique identifier (e.g. UUID) for the task, generated by the server for a
     * new task.
     * </pre>
     *
     * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier (e.g. UUID) for the task, generated by the server for a
     * new task.
     * </pre>
     *
     * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier (e.g. UUID) for the task, generated by the server for a
     * new task.
     * </pre>
     *
     * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier (e.g. UUID) for the task, generated by the server for a
     * new task.
     * </pre>
     *
     * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier (e.g. UUID) for the task, generated by the server for a
     * new task.
     * </pre>
     *
     * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contextId_ = "";
    /**
     * <pre>
     * Unique identifier (e.g. UUID) for the contextual collection of interactions
     * (tasks and messages).
     * </pre>
     *
     * <code>string context_id = 2;</code>
     * @return The contextId.
     */
    public java.lang.String getContextId() {
      java.lang.Object ref = contextId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contextId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier (e.g. UUID) for the contextual collection of interactions
     * (tasks and messages).
     * </pre>
     *
     * <code>string context_id = 2;</code>
     * @return The bytes for contextId.
     */
    public com.google.protobuf.ByteString
        getContextIdBytes() {
      java.lang.Object ref = contextId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contextId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier (e.g. UUID) for the contextual collection of interactions
     * (tasks and messages).
     * </pre>
     *
     * <code>string context_id = 2;</code>
     * @param value The contextId to set.
     * @return This builder for chaining.
     */
    public Builder setContextId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contextId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier (e.g. UUID) for the contextual collection of interactions
     * (tasks and messages).
     * </pre>
     *
     * <code>string context_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContextId() {
      
      contextId_ = getDefaultInstance().getContextId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier (e.g. UUID) for the contextual collection of interactions
     * (tasks and messages).
     * </pre>
     *
     * <code>string context_id = 2;</code>
     * @param value The bytes for contextId to set.
     * @return This builder for chaining.
     */
    public Builder setContextIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contextId_ = value;
      onChanged();
      return this;
    }

    private org.a2aproject.sdk.grpc.TaskStatus status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.a2aproject.sdk.grpc.TaskStatus, org.a2aproject.sdk.grpc.TaskStatus.Builder, org.a2aproject.sdk.grpc.TaskStatusOrBuilder> statusBuilder_;
    /**
     * <pre>
     * The current status of a `Task`, including `state` and a `message`.
     * </pre>
     *
     * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <pre>
     * The current status of a `Task`, including `state` and a `message`.
     * </pre>
     *
     * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The status.
     */
    public org.a2aproject.sdk.grpc.TaskStatus getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? org.a2aproject.sdk.grpc.TaskStatus.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The current status of a `Task`, including `state` and a `message`.
     * </pre>
     *
     * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setStatus(org.a2aproject.sdk.grpc.TaskStatus value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The current status of a `Task`, including `state` and a `message`.
     * </pre>
     *
     * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setStatus(
        org.a2aproject.sdk.grpc.TaskStatus.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The current status of a `Task`, including `state` and a `message`.
     * </pre>
     *
     * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeStatus(org.a2aproject.sdk.grpc.TaskStatus value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            org.a2aproject.sdk.grpc.TaskStatus.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The current status of a `Task`, including `state` and a `message`.
     * </pre>
     *
     * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The current status of a `Task`, including `state` and a `message`.
     * </pre>
     *
     * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public org.a2aproject.sdk.grpc.TaskStatus.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The current status of a `Task`, including `state` and a `message`.
     * </pre>
     *
     * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public org.a2aproject.sdk.grpc.TaskStatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            org.a2aproject.sdk.grpc.TaskStatus.getDefaultInstance() : status_;
      }
    }
    /**
     * <pre>
     * The current status of a `Task`, including `state` and a `message`.
     * </pre>
     *
     * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.a2aproject.sdk.grpc.TaskStatus, org.a2aproject.sdk.grpc.TaskStatus.Builder, org.a2aproject.sdk.grpc.TaskStatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.a2aproject.sdk.grpc.TaskStatus, org.a2aproject.sdk.grpc.TaskStatus.Builder, org.a2aproject.sdk.grpc.TaskStatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private java.util.List<org.a2aproject.sdk.grpc.Artifact> artifacts_ =
      java.util.Collections.emptyList();
    private void ensureArtifactsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        artifacts_ = new java.util.ArrayList<org.a2aproject.sdk.grpc.Artifact>(artifacts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.a2aproject.sdk.grpc.Artifact, org.a2aproject.sdk.grpc.Artifact.Builder, org.a2aproject.sdk.grpc.ArtifactOrBuilder> artifactsBuilder_;

    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public java.util.List<org.a2aproject.sdk.grpc.Artifact> getArtifactsList() {
      if (artifactsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(artifacts_);
      } else {
        return artifactsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public int getArtifactsCount() {
      if (artifactsBuilder_ == null) {
        return artifacts_.size();
      } else {
        return artifactsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public org.a2aproject.sdk.grpc.Artifact getArtifacts(int index) {
      if (artifactsBuilder_ == null) {
        return artifacts_.get(index);
      } else {
        return artifactsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public Builder setArtifacts(
        int index, org.a2aproject.sdk.grpc.Artifact value) {
      if (artifactsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArtifactsIsMutable();
        artifacts_.set(index, value);
        onChanged();
      } else {
        artifactsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public Builder setArtifacts(
        int index, org.a2aproject.sdk.grpc.Artifact.Builder builderForValue) {
      if (artifactsBuilder_ == null) {
        ensureArtifactsIsMutable();
        artifacts_.set(index, builderForValue.build());
        onChanged();
      } else {
        artifactsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public Builder addArtifacts(org.a2aproject.sdk.grpc.Artifact value) {
      if (artifactsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArtifactsIsMutable();
        artifacts_.add(value);
        onChanged();
      } else {
        artifactsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public Builder addArtifacts(
        int index, org.a2aproject.sdk.grpc.Artifact value) {
      if (artifactsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArtifactsIsMutable();
        artifacts_.add(index, value);
        onChanged();
      } else {
        artifactsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public Builder addArtifacts(
        org.a2aproject.sdk.grpc.Artifact.Builder builderForValue) {
      if (artifactsBuilder_ == null) {
        ensureArtifactsIsMutable();
        artifacts_.add(builderForValue.build());
        onChanged();
      } else {
        artifactsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public Builder addArtifacts(
        int index, org.a2aproject.sdk.grpc.Artifact.Builder builderForValue) {
      if (artifactsBuilder_ == null) {
        ensureArtifactsIsMutable();
        artifacts_.add(index, builderForValue.build());
        onChanged();
      } else {
        artifactsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public Builder addAllArtifacts(
        java.lang.Iterable<? extends org.a2aproject.sdk.grpc.Artifact> values) {
      if (artifactsBuilder_ == null) {
        ensureArtifactsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, artifacts_);
        onChanged();
      } else {
        artifactsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public Builder clearArtifacts() {
      if (artifactsBuilder_ == null) {
        artifacts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        artifactsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public Builder removeArtifacts(int index) {
      if (artifactsBuilder_ == null) {
        ensureArtifactsIsMutable();
        artifacts_.remove(index);
        onChanged();
      } else {
        artifactsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public org.a2aproject.sdk.grpc.Artifact.Builder getArtifactsBuilder(
        int index) {
      return getArtifactsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public org.a2aproject.sdk.grpc.ArtifactOrBuilder getArtifactsOrBuilder(
        int index) {
      if (artifactsBuilder_ == null) {
        return artifacts_.get(index);  } else {
        return artifactsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public java.util.List<? extends org.a2aproject.sdk.grpc.ArtifactOrBuilder> 
         getArtifactsOrBuilderList() {
      if (artifactsBuilder_ != null) {
        return artifactsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(artifacts_);
      }
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public org.a2aproject.sdk.grpc.Artifact.Builder addArtifactsBuilder() {
      return getArtifactsFieldBuilder().addBuilder(
          org.a2aproject.sdk.grpc.Artifact.getDefaultInstance());
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public org.a2aproject.sdk.grpc.Artifact.Builder addArtifactsBuilder(
        int index) {
      return getArtifactsFieldBuilder().addBuilder(
          index, org.a2aproject.sdk.grpc.Artifact.getDefaultInstance());
    }
    /**
     * <pre>
     * A set of output artifacts for a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
     */
    public java.util.List<org.a2aproject.sdk.grpc.Artifact.Builder> 
         getArtifactsBuilderList() {
      return getArtifactsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.a2aproject.sdk.grpc.Artifact, org.a2aproject.sdk.grpc.Artifact.Builder, org.a2aproject.sdk.grpc.ArtifactOrBuilder> 
        getArtifactsFieldBuilder() {
      if (artifactsBuilder_ == null) {
        artifactsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.a2aproject.sdk.grpc.Artifact, org.a2aproject.sdk.grpc.Artifact.Builder, org.a2aproject.sdk.grpc.ArtifactOrBuilder>(
                artifacts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        artifacts_ = null;
      }
      return artifactsBuilder_;
    }

    private java.util.List<org.a2aproject.sdk.grpc.Message> history_ =
      java.util.Collections.emptyList();
    private void ensureHistoryIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        history_ = new java.util.ArrayList<org.a2aproject.sdk.grpc.Message>(history_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.a2aproject.sdk.grpc.Message, org.a2aproject.sdk.grpc.Message.Builder, org.a2aproject.sdk.grpc.MessageOrBuilder> historyBuilder_;

    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public java.util.List<org.a2aproject.sdk.grpc.Message> getHistoryList() {
      if (historyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(history_);
      } else {
        return historyBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public int getHistoryCount() {
      if (historyBuilder_ == null) {
        return history_.size();
      } else {
        return historyBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public org.a2aproject.sdk.grpc.Message getHistory(int index) {
      if (historyBuilder_ == null) {
        return history_.get(index);
      } else {
        return historyBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public Builder setHistory(
        int index, org.a2aproject.sdk.grpc.Message value) {
      if (historyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryIsMutable();
        history_.set(index, value);
        onChanged();
      } else {
        historyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public Builder setHistory(
        int index, org.a2aproject.sdk.grpc.Message.Builder builderForValue) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.set(index, builderForValue.build());
        onChanged();
      } else {
        historyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public Builder addHistory(org.a2aproject.sdk.grpc.Message value) {
      if (historyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryIsMutable();
        history_.add(value);
        onChanged();
      } else {
        historyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public Builder addHistory(
        int index, org.a2aproject.sdk.grpc.Message value) {
      if (historyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryIsMutable();
        history_.add(index, value);
        onChanged();
      } else {
        historyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public Builder addHistory(
        org.a2aproject.sdk.grpc.Message.Builder builderForValue) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.add(builderForValue.build());
        onChanged();
      } else {
        historyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public Builder addHistory(
        int index, org.a2aproject.sdk.grpc.Message.Builder builderForValue) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.add(index, builderForValue.build());
        onChanged();
      } else {
        historyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public Builder addAllHistory(
        java.lang.Iterable<? extends org.a2aproject.sdk.grpc.Message> values) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, history_);
        onChanged();
      } else {
        historyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public Builder clearHistory() {
      if (historyBuilder_ == null) {
        history_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        historyBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public Builder removeHistory(int index) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.remove(index);
        onChanged();
      } else {
        historyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public org.a2aproject.sdk.grpc.Message.Builder getHistoryBuilder(
        int index) {
      return getHistoryFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public org.a2aproject.sdk.grpc.MessageOrBuilder getHistoryOrBuilder(
        int index) {
      if (historyBuilder_ == null) {
        return history_.get(index);  } else {
        return historyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public java.util.List<? extends org.a2aproject.sdk.grpc.MessageOrBuilder> 
         getHistoryOrBuilderList() {
      if (historyBuilder_ != null) {
        return historyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(history_);
      }
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public org.a2aproject.sdk.grpc.Message.Builder addHistoryBuilder() {
      return getHistoryFieldBuilder().addBuilder(
          org.a2aproject.sdk.grpc.Message.getDefaultInstance());
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public org.a2aproject.sdk.grpc.Message.Builder addHistoryBuilder(
        int index) {
      return getHistoryFieldBuilder().addBuilder(
          index, org.a2aproject.sdk.grpc.Message.getDefaultInstance());
    }
    /**
     * <pre>
     * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
     * The history of interactions from a `Task`.
     * </pre>
     *
     * <code>repeated .lf.a2a.v1.Message history = 5;</code>
     */
    public java.util.List<org.a2aproject.sdk.grpc.Message.Builder> 
         getHistoryBuilderList() {
      return getHistoryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.a2aproject.sdk.grpc.Message, org.a2aproject.sdk.grpc.Message.Builder, org.a2aproject.sdk.grpc.MessageOrBuilder> 
        getHistoryFieldBuilder() {
      if (historyBuilder_ == null) {
        historyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.a2aproject.sdk.grpc.Message, org.a2aproject.sdk.grpc.Message.Builder, org.a2aproject.sdk.grpc.MessageOrBuilder>(
                history_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        history_ = null;
      }
      return historyBuilder_;
    }

    private com.google.protobuf.Struct metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> metadataBuilder_;
    /**
     * <pre>
     * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
     * A key/value object to store custom metadata about a task.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 6;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return metadataBuilder_ != null || metadata_ != null;
    }
    /**
     * <pre>
     * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
     * A key/value object to store custom metadata about a task.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 6;</code>
     * @return The metadata.
     */
    public com.google.protobuf.Struct getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
     * A key/value object to store custom metadata about a task.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 6;</code>
     */
    public Builder setMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
        onChanged();
      } else {
        metadataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
     * A key/value object to store custom metadata about a task.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 6;</code>
     */
    public Builder setMetadata(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
        onChanged();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
     * A key/value object to store custom metadata about a task.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 6;</code>
     */
    public Builder mergeMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (metadata_ != null) {
          metadata_ =
            com.google.protobuf.Struct.newBuilder(metadata_).mergeFrom(value).buildPartial();
        } else {
          metadata_ = value;
        }
        onChanged();
      } else {
        metadataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
     * A key/value object to store custom metadata about a task.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 6;</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        metadata_ = null;
        onChanged();
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
     * A key/value object to store custom metadata about a task.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 6;</code>
     */
    public com.google.protobuf.Struct.Builder getMetadataBuilder() {
      
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
     * A key/value object to store custom metadata about a task.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 6;</code>
     */
    public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <pre>
     * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
     * A key/value object to store custom metadata about a task.
     * </pre>
     *
     * <code>.google.protobuf.Struct metadata = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lf.a2a.v1.Task)
  }

  // @@protoc_insertion_point(class_scope:lf.a2a.v1.Task)
  private static final org.a2aproject.sdk.grpc.Task DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.a2aproject.sdk.grpc.Task();
  }

  public static org.a2aproject.sdk.grpc.Task getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Task>
      PARSER = new com.google.protobuf.AbstractParser<Task>() {
    @java.lang.Override
    public Task parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Task(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Task> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Task> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.a2aproject.sdk.grpc.Task getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

